ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.budgienews.server.ServerKt.module ]
    }
}

database {
    jdbcUrl = "jdbc:mysql://213.165.91.6:3306/s4152_budgie_news"
    username = "u4152_qieZLFnJ6R"
    password = "L1WTzeaBkequ6caOCOq0gWx="
}
